#!/usr/bin/env python3
"""Generate the Q15 exp() lookup tables used by softmax_q15_lut().

Run from the repo root:

    python3 tools/gen_exp_tables.py

and paste the output into arduino/softmax_power_bench/softmax_kernels.cpp.
Kept in the repo so the tables can be regenerated / audited instead of
being magic numbers.
"""

import math

Q15 = 32768
Q15_MAX = 32767  # 1.0 is not representable in Q15, saturate instead


def q15(x):
    return min(Q15_MAX, int(round(x * Q15)))


def emit(name, values, per_line=8):
    print(f"const uint16_t {name}[{len(values)}] PROGMEM = {{")
    for i in range(0, len(values), per_line):
        chunk = ", ".join("%5d" % v for v in values[i : i + per_line])
        print(f"    {chunk},")
    print("};")
    print()


def main():
    # exp(-n) for n = 0 .. 15 (integer part of the exponent).
    # exp(-16) = 1.1e-7 which is 0 in Q15, so 16 entries is the whole
    # useful range and anything beyond it is flushed to zero.
    int_tab = [q15(math.exp(-n)) for n in range(16)]

    # exp(-f) for f = k/16, k = 0 .. 16 (fractional part). 17 entries so
    # the kernel can linearly interpolate between k and k+1.
    frac_tab = [q15(math.exp(-(k / 16.0))) for k in range(17)]

    print("/* Generated by tools/gen_exp_tables.py - do not edit by hand. */")
    emit("kExpIntQ15", int_tab)
    emit("kExpFracQ15", frac_tab)

    # Report the accuracy of the interpolated fractional term so the
    # error budget of the kernel is documented rather than guessed.
    worst = 0.0
    for i in range(256):
        f = i / 256.0
        k, r = i >> 4, i & 15
        lo, hi = frac_tab[k], frac_tab[k + 1]
        approx = (lo + ((hi - lo) * r >> 4)) / Q15
        worst = max(worst, abs(approx - math.exp(-f)) / math.exp(-f))
    print("/* interpolated exp(-frac) max relative error: %.2e */" % worst)


if __name__ == "__main__":
    main()
